# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"box2polygon": "00_core.ipynb",
         "slice_box": "00_core.ipynb",
         "intersection_list": "00_core.ipynb",
         "slice_one": "00_core.ipynb",
         "slice_all": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://mnpinto.github.io/splitbbox/"

git_url = "https://github.com/mnpinto/splitbbox/tree/master/"

def custom_doc_links(name): return None
